name: "godot-export-win-mac-linux"
on: push

jobs:
  export-windows:
    name: Windows Export
    uses: ioribranford/yuri2021/.github/workflows/godot-export.yml@github-actions
    with:
      game_name: yuri2021
      platform: windows
      export_preset: Windows Desktop

  export-linux:
    name: Linux Export
    uses: ioribranford/yuri2021/.github/workflows/godot-export.yml@github-actions
    with:
      game_name: yuri2021
      platform: linux
      export_preset: Linux/X11

  export-mac:
    name: Mac Export
    uses: ioribranford/yuri2021/.github/workflows/godot-export.yml@github-actions
    with:
      game_name: yuri2021
      platform: mac
      export_preset: Mac OSX
